### PR TITLE
Switch to Flowzone

### PR DESCRIPTION
**Pull request by ab77**
Change-type: patch

### CODE REVIEW

**Comment by ab77** [comment]
@zwhitchcox can you please glance over this - it builds/tests on all platforms.

**Comment by ab77** [comment]
@zwhitchcox we can probably delete all of these also: https://github.com/balena-io-modules/drivelist/releases

**Comment by zwhitchcox** [comment]
Nice! LGTM @ab77

**Comment by zwhitchcox** [comment]
Yes, probably no one is depending on those...I actually do want to try to prebuild at some point, just because it makes things a lot simpler for people, but I'm not sure how that works with flowzone

**Review by zwhitchcox — APPROVED** [review]

**Pull request merged**
