### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by lurch** [comment]
It says:
```
All notable changes to this project will be documented in this file
automatically by Versionist. DO NOT EDIT THIS FILE MANUALLY!
```
at the top of this file? :thinking:

**Comment by cclauss** [comment]
Does `Versionist` include spellchecking?

**Comment by ab77** [comment]
> Does `Versionist` include spellchecking?

I am afraid it does not reword commit messages.

**Comment by ab77** [comment]
I am going to close this since it's a no-op.

**Pull request closed without merging**
